version: '2'
services:
  db:
    image: "postgres:9.3"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWOD=somepass
      - POSTGRES_DB=preparadb
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data